config:
  send_anonymous_usage_stats: False
  use_colors: True

sdcs_data:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      user: "postgres"
      pass: 
      port: 5432
      dbname: "sdcs"
      schema: "sdcs"
