{% macro flatten_static(static, prefix) %}
{{ static }} ->> 'id' as {{ prefix }}id,
{{ static }} ->> 'name' as {{ prefix }}name,
{{ static }} ->> 'type' as {{ prefix }}type,
{{ static }} -> 'position' ->> 'u' as {{ prefix }}position_u,
{{ static }} -> 'position' ->> 'v' as {{ prefix }}position_v,
{{ static }} -> 'position' ->> 'alt' as {{ prefix }}position_alt,
{{ static }} -> 'position' ->> 'lat' as {{ prefix }}position_lat,
{{ static }} -> 'position' ->> 'lon' as {{ prefix }}position_lon,
{{ static }} -> 'velocity' ->> 'speed' as {{ prefix }}velocity_speed,
{{ static }} -> 'velocity' ->> 'heading' as {{ prefix }}velocity_heading,
{{ static }} -> 'velocity' -> 'velocity' ->> 'x' as {{ prefix }}velocity_x,
{{ static }} -> 'velocity' -> 'velocity' ->> 'y' as {{ prefix }}velocity_y,
{{ static }} -> 'velocity' -> 'velocity' ->> 'z' as {{ prefix }}velocity_z,
{{ static }} ->> 'coalition' as {{ prefix }}coalition,
{{ static }} -> 'orientation' -> 'up' ->> 'x' as {{ prefix }}orientation_up_x,
{{ static }} -> 'orientation' -> 'up' ->> 'y' as {{ prefix }}orientation_up_y,
{{ static }} -> 'orientation' -> 'up' ->> 'z' as {{ prefix }}orientation_up_z,
{{ static }} -> 'orientation' ->> 'yaw' as {{ prefix }}orientation_yaw,
{{ static }} -> 'orientation' ->> 'roll' as {{ prefix }}orientation_roll,
{{ static }} -> 'orientation' ->> 'pitch' as {{ prefix }}orientation_pitch,
{{ static }} -> 'orientation' -> 'right' ->> 'x' as {{ prefix }}orientation_right_x,
{{ static }} -> 'orientation' -> 'right' ->> 'y' as {{ prefix }}orientation_right_y,
{{ static }} -> 'orientation' -> 'right' ->> 'z' as {{ prefix }}orientation_right_z,
{{ static }} -> 'orientation' -> 'forward' ->> 'x' as {{ prefix }}orientation_forward_x,
{{ static }} -> 'orientation' -> 'forward' ->> 'y' as {{ prefix }}orientation_forward_y,
{{ static }} -> 'orientation' -> 'forward' ->> 'z' as {{ prefix }}orientation_forward_z,
{{ static }} -> 'orientation' ->> 'heading' as {{ prefix }}orientation_heading
{% endmacro %}
