{% macro flatten_unit(unit, prefix) %}
    {{ unit }} ->> 'id' as {{ prefix }}id,
    {{ unit }} ->> 'fuel' as {{ prefix }}fuel,
    {{ unit }} ->> 'name' as {{ prefix }}name,
    {{ unit }} ->> 'type' as {{ prefix }}type,
    {{ unit }} -> 'group' ->> 'id' as {{ prefix }}group_id,
    {{ unit }} -> 'group' ->> 'name' as {{ prefix }}group_name,
    {{ unit }} -> 'group' ->> 'category' as {{ prefix }}group_category,
    {{ unit }} -> 'group' ->> 'coalition' as {{ prefix }}group_coalition,
    {{ unit }} ->> 'inAir' as {{ prefix }}in_air,
    {{ unit }} ->> 'callsign' as {{ prefix }}callsign,
    {{ unit }} -> 'position' ->> 'u' as {{ prefix }}position_u,
    {{ unit }} -> 'position' ->> 'v' as {{ prefix }}position_v,
    {{ unit }} -> 'position' ->> 'alt' as {{ prefix }}position_alt,
    {{ unit }} -> 'position' ->> 'lat' as {{ prefix }}position_lat,
    {{ unit }} -> 'position' ->> 'lon' as {{ prefix }}position_lon,
    {{ unit }} -> 'velocity' ->> 'speed' as {{ prefix }}velocity_speed,
    {{ unit }} -> 'velocity' ->> 'heading' as {{ prefix }}velocity_heading,
    {{ unit }} -> 'velocity' -> 'velocity' ->> 'x' as {{ prefix }}velocity_x,
    {{ unit }} -> 'velocity' -> 'velocity' ->> 'y' as {{ prefix }}velocity_y,
    {{ unit }} -> 'velocity' -> 'velocity' ->> 'z' as {{ prefix }}velocity_z,
    {{ unit }} ->> 'coalition' as {{ prefix }}coalition,
    {{ unit }} ->> 'playerName' as {{ prefix }}player_name,
    {{ unit }} -> 'orientation' -> 'up' ->> 'x' as {{ prefix }}orientation_up_x,
    {{ unit }} -> 'orientation' -> 'up' ->> 'y' as {{ prefix }}orientation_up_y,
    {{ unit }} -> 'orientation' -> 'up' ->> 'z' as {{ prefix }}orientation_up_z,
    {{ unit }} -> 'orientation' ->> 'yaw' as {{ prefix }}orientation_yaw,
    {{ unit }} -> 'orientation' ->> 'roll' as {{ prefix }}orientation_roll,
    {{ unit }} -> 'orientation' ->> 'pitch' as {{ prefix }}orientation_pitch,
    {{ unit }} -> 'orientation' -> 'right' ->> 'x' as {{ prefix }}orientation_right_x,
    {{ unit }} -> 'orientation' -> 'right' ->> 'y' as {{ prefix }}orientation_right_y,
    {{ unit }} -> 'orientation' -> 'right' ->> 'z' as {{ prefix }}orientation_right_z,
    {{ unit }} -> 'orientation' -> 'forward' ->> 'x' as {{ prefix }}orientation_forward_x,
    {{ unit }} -> 'orientation' -> 'forward' ->> 'y' as {{ prefix }}orientation_forward_y,
    {{ unit }} -> 'orientation' -> 'forward' ->> 'z' as {{ prefix }}orientation_forward_z,
    {{ unit }} -> 'orientation' ->> 'heading' as {{ prefix }}orientation_heading,
    {{ unit }} ->> 'numberInGroup' as {{ prefix }}number_in_group
{% endmacro %}
