-- models/staging/flat_events_t1.sql

SELECT
    id,
    campaign_id,
    initiator_user_id,
    target_user_id,
    time AS event_time,
    data->>'pilotDead' AS pilotDead,
    data->>'playerLeaveUnit' AS playerLeaveUnit,
    data->>'markChange' AS markChange,
    data->>'takeoff' AS takeoff,
    data->>'disconnect' AS disconnect,
    data->>'unitLost' AS unitLost,
    data->>'event' AS event,
    data->>'groupCommand' AS groupCommand,
    data->>'engineStartup' AS engineStartup,
    data->>'shootingEnd' AS shootingEnd,
    data->>'ejection' AS ejection,
    data->>'crash' AS crash,
    data->>'land' AS land,
    data->>'playerChangeSlot' AS playerChangeSlot,
    data->>'refueling' AS refueling,
    data->>'markAdd' AS markAdd,
    data->>'dead' AS dead,
    data->>'baseCapture' AS baseCapture,
    data->>'time' AS tme,
    data->>'birth' AS birth,
    data->>'engineShutdown' AS engineShutdown,
    data->>'hit' AS hit,
    data->>'shootingStart' AS shootingStart,
    data->>'score' AS score,
    data->>'markRemove' AS markRemove,
    data->>'connect' AS playerConnect,
    data->>'kill' AS kill,
    data->>'refuelingStop' AS refuelingStop,
    data->>'playerSendChat' AS playerSendChat

FROM public.events
